wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.8.11
    start_time: 1647901172
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 7
      - 13
      4: 3.8.11
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
channels:
  desc: null
  value: 3
depth:
  desc: null
  value: 2
dim:
  desc: null
  value: 512
dim_head:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.0
emb_dropout:
  desc: null
  value: 0.0
heads:
  desc: null
  value: 2
image_size:
  desc: null
  value:
  - 192
  - 160
kl_weight:
  desc: null
  value: 1.0e-05
lr:
  desc: null
  value: 1.0e-05
mlp_dim:
  desc: null
  value: 512
patch_size:
  desc: null
  value: 16
