wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.11
    start_time: 1647879825
    t:
      1:
      - 1
      - 9
      - 41
      2:
      - 1
      - 9
      - 41
      3:
      - 7
      - 13
      4: 3.8.11
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
channels:
  desc: null
  value: 3
depth:
  desc: null
  value: 12
dim:
  desc: null
  value: 1024
dim_head:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.5
emb_dropout:
  desc: null
  value: 0.3
heads:
  desc: null
  value: 16
image_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 3.0e-05
mlp_dim:
  desc: null
  value: 2048
num_classes:
  desc: null
  value: 10
optim_choice:
  desc: null
  value: Adam
patch_size:
  desc: null
  value: 8
pool:
  desc: null
  value: cls
